### ISSUE TITLE
Failed to locate image 'ok.png'

### ISSUE THREAD

**Issue by tordanik** [JOSM/josm-gridify#13] opened 2020-11-06 15:34 UTC
Attempting to use Gridify (using the keyboard shortcut or the menu item) fails – the dialog does not appear, and there is no other visible effect. There is no error message in JOSM's graphical user interface, but an exception stack trace is printed to console.

This is the current JOSM tested build (17084), with Gridify version 1588746833.

### Exception on console:

```
org.openstreetmap.josm.tools.JosmRuntimeException: Fatal: failed to locate image 'ok.png'. This is a serious configuration problem. JOSM will stop working.
	at org.openstreetmap.josm.tools.ImageProvider.getResource(ImageProvider.java:717)
	at org.openstreetmap.josm.tools.ImageProvider.get(ImageProvider.java:655)
	at org.openstreetmap.josm.tools.ImageProvider.get(ImageProvider.java:823)
	at org.openstreetmap.josm.gui.ExtendedDialog.setButtonIcons(ExtendedDialog.java:187)
	at nl.jeroenhoek.josm.gridify.ui.GridifySettingsDialog.<init>(GridifySettingsDialog.java:106)
	at nl.jeroenhoek.josm.gridify.GridifyAction.performGridifyAction(GridifyAction.java:106)
	at nl.jeroenhoek.josm.gridify.GridifyAction.actionPerformed(GridifyAction.java:66)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:842)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:886)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

### JOSM Status Report:

```
{{{
URL:https://josm.openstreetmap.de/svn/trunk
Repository:UUID: 0c6e7542-c601-0410-84e7-c038aed88b3b
Last:Changed Date: 2020-10-03 13:42:38 +0200 (Sat, 03 Oct 2020)
Build-Date:2020-10-04 01:30:47
Revision:17084
Relative:URL: ^/trunk

Identification: JOSM/1.5 (17084 en) Linux Ubuntu 20.04.1 LTS
Memory Usage: 1503 MB / 3541 MB (759 MB allocated, but free)
Java version: 1.8.0_272-8u272-b10-0ubuntu1~20.04-b10, Private Build, OpenJDK 64-Bit Server VM
Look and Feel: javax.swing.plaf.metal.MetalLookAndFeel
Screen: :0.0 1920x1080 (scaling 1.0x1.0)
Maximum Screen Size: 1920x1080
Best cursor sizes: 16x16 -> 16x16, 32x32 -> 32x32
Desktop environment: ubuntu:GNOME
Java package: openjdk-8-jre:amd64-8u272-b10-0ubuntu1~20.04
Java ATK Wrapper package: libatk-wrapper-java:all-0.37.1-1
libcommons-compress-java: libcommons-compress-java:all-1.19-1
libcommons-logging-java: libcommons-logging-java:all-1.2-2
fonts-noto: fonts-noto:-
Dataset consistency test: No problems found

Plugins:
+ QuickLabel (18)
+ RoadSigns (35510)
+ apache-commons (35524)
+ apache-http (35092)
+ buildings_tools (35579)
+ ejml (35313)
+ geotools (35169)
+ graphview (35405)
+ gridify (1588746833)
+ jaxb (35092)
+ jna (35092)
+ jogl (1.2.3)
+ jts (35122)
+ kendzi3d (1.0.205)
+ kendzi3d-resources (0.0.2)
+ log4j (35092)
+ opendata (35513)
+ pbf (35636)
+ reverter (35638)
+ shrinkwrap (v1.0.3)
+ utilsplugin2 (35624)
+ wikipedia (1.1.4)

Tagging presets:
+ https://github.com/kendzi/Simple3dBuildingsPreset/releases/download/0.9_2018-05-08/s3db-preset.zip

Map paint styles:
- https://josm.openstreetmap.de/josmfile?page=Styles/Enhanced_Lane_and_Road_Attributes&zip=1
}}}
```

**Comment by jdhoek** [comment] 2020-11-06 15:36
This looks like a duplicate of #10. Could you try deleting the plugin and redownloading?

**Comment by tordanik** [comment] 2020-11-06 16:04
Ok, turns out that while disabling the plugin in the settings, restarting JOSM, and re-enabling the plugin wasn't enough to resolve the error, manually deleting the .jar from my ~/.josm/plugins directory got rid of it. So the exception about .png file extension was apparently caused by #10.

However, there's still something odd going on here: The version number listed for gridify is the same as before (1588746833), and the Plugin-Version and Plugin-Date in the manifest files of the two gridifiy.jar archives are identical, even though the .jar files themselves are otherwise different from each other. Could this hint at a versioning issue that would have caused me (and maybe other users?) to not have received the automatic update with the bug fix?

In any case, the file extension issue is indeed fixed in the latest version. Thanks for the impressively fast response!

**Comment by jdhoek** [comment] 2020-11-06 16:15
Yes, there seems to be an issue with the version number. I'll fix this in the next release.

> Thanks for the impressively fast response!

No problem. Happy mapping.

**Closed by jdhoek** 2020-11-06 16:15 UTC
